vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>ga", vim.cmd.Gwrite)
vim.keymap.set("n", "<leader>gc", function()
    vim.cmd.Git('commit')
end)
vim.keymap.set("n", "<leader>gp", function()
    vim.cmd.Git('push')
end)
vim.keymap.set("n", "<leader>gP", function()
    vim.cmd.Git({ 'pull', "--rebase" })
end)
