vim.cmd "autocmd BufWritePre *.vim :lua vim.lsp.buf.format()"
vim.cmd "autocmd BufWritePre *.lua :lua vim.lsp.buf.format()"
vim.cmd "autocmd BufWritePre *.v :lua vim.lsp.buf.format()"
vim.cmd "autocmd BufWritePre *.sv :lua vim.lsp.buf.format()"
vim.cmd "autocmd BufWritePre *.py :lua vim.lsp.buf.format()"
vim.cmd "autocmd BufWritePre *.sh :lua vim.lsp.buf.format()"
vim.cmd "autocmd BufWritePre *.json :lua vim.lsp.buf.format()"
